### ISSUE TITLE
Unexpected parent dependency exception when belongsTo alignment is used.

### ISSUE THREAD

**Issue by chali** [nebula-plugins/gradle-nebula-integration#13]
```
Caused by: java.lang.IllegalStateException: Unexpected parent dependency id 1419. Seen ids: [2, 2053, 1036, 1037, 1038, 2068, 2075, 2077, 2079, 2081, 2083, 2096, 2101, 2115, 2116, 71, 72, 73, 74, 75, 2123, 77, 78, 2126, 80, 81, 2129, 82, 83, 1107, 1108, 1109, 1110, 2134, 1111, 2135, 1112, 1113, 1114, 1115, 1117, 1118, 95, 1119, 96, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 2153, 1130, 2154, 1131, 1132, 1133, 1134, 111, 1135, 1136, 1137, 2161, 114, 1138, 115, 1139, 116, 1140, 2166, 2168, 1145, 1146, 2170, 1149, 2175, 1152, 2189, 2190, 151, 152, 153, 1177, 154, 155, 156, 157, 2205, 158, 159, 160, 161, 1187, 1188, 1189, 1196, 2226, 1207, 1212, 2236, 1213, 2237, 1216, 1221, 1222, 2248, 1225, 2249, 2250, 2251, 2252, 205, 1230, 2255, 210, 1235, 1238, 1245, 1246, 1255, 1261, 241, 242, 1280, 1281, 1283, 1284, 1285, 262, 1286, 1287, 264, 267, 1292, 269, 1297, 278, 281, 282, 283, 284, 285, 286, 287, 289, 290, 291, 1315, 1316, 1318, 1329, 1330, 1331, 1332, 1333, 1352, 1354, 337, 1361, 339, 1364, 341, 344, 347, 349, 351, 353, 1378, 356, 358, 1382, 1386, 363, 1389, 366, 368, 1394, 373, 1397, 375, 1400, 377, 1403, 380, 382, 1406, 385, 1409, 387, 389, 391, 393, 395, 397, 1422, 400, 402, 404, 406, 408, 410, 412, 415, 420, 1444, 1446, 423, 1448, 1454, 431, 1456, 1460, 1465, 1467, 1470, 1473, 1479, 458, 459, 461, 1486, 1491, 1492, 470, 471, 1495, 477, 478, 485, 486, 487, 492, 1518, 1519, 1520, 1521, 1524, 504, 1529, 506, 1530, 507, 1535, 514, 515, 516, 1550, 1551, 1552, 1553, 1562, 1567, 1579, 563, 564, 565, 566, 567, 1591, 568, 1592, 569, 1593, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 596, 597, 598, 599, 600, 1630, 1631, 1632, 610, 612, 1637, 617, 1642, 1643, 1648, 632, 633, 634, 635, 636, 637, 638, 1666, 1667, 1668, 645, 646, 647, 1671, 1676, 1685, 662, 1686, 663, 1687, 664, 665, 666, 667, 668, 1698, 1699, 1710, 1717, 1718, 1719, 697, 698, 1722, 699, 700, 701, 702, 703, 704, 1728, 705, 1729, 706, 707, 708, 1732, 709, 710, 718, 729, 1767, 744, 745, 1770, 752, 753, 754, 767, 768, 771, 775, 802, 1826, 805, 1829, 820, 1844, 1849, 827, 1854, 831, 1855, 1858, 1876, 1878, 1880, 1882, 1884, 1886, 1888, 1890, 1892, 1894, 871, 1896, 873, 1898, 1900, 1902, 880, 883, 1911, 1913, 890, 1914, 893, 1919, 1920, 898, 902, 904, 1929, 906, 908, 910, 1934, 1935, 912, 914, 1942, 921, 1947, 924, 928, 931, 934, 937, 944, 1972, 1973, 957, 958, 959, 960, 965, 966, 969, 1997, 974, 975, 2000, 978, 2005, 2010, 987, 988, 989, 990, 993, 996, 999, 2024, 1002, 1005, 1010, 1011, 2038, 1021, 1022]
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder.deserialize(TransientConfigurationResultsBuilder.java:192)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder.access$200(TransientConfigurationResultsBuilder.java:49)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder$6$1.read(TransientConfigurationResultsBuilder.java:135)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder$6$1.read(TransientConfigurationResultsBuilder.java:133)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:128)
        ... 117 more
```

I'm getting this exception after following calls:
`GRADLE_USER_HOME=./.gradleUserHome ./gradlew -Dnebula.features.coreAlignmentSupport=false -qs gL --offline`
`GRADLE_USER_HOME=./.gradleUserHome ./gradlew -Dnebula.features.coreAlignmentSupport=true -qs gL --offline`

**Comment by chali** [comment]
Example project will be shared privately.

**Comment by chali** [comment]
We cannot reproduce this issue anymore so we cannot provide an example. I'm closing it for now and we can get back to it if it will appear again.
