### ISSUE TITLE
`CacheableRule` does not appear to be working with `ComponentMetadataRule`

### ISSUE THREAD

**Issue by rpalcolea** [nebula-plugins/gradle-nebula-integration#42]
Hi @ljacomet  @bigdaz  @melix 

We were trying to implement a `ComponentMetadataRule` using `CacheableRule`.

However, it seems that the rule is not getting cache across builds and it gets executed twice.

To give an example, took the same repo we shared for the `candidate` issue and added the rule in there -> https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/cache-rule-issue

We have a `CacheableStatusRule` annotated with `@CacheableRule` in https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/cache-rule-issue and applying it in https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/cache-rule-issue/src/main/groovy/gradle5/rc/issue/MyPlugin.groovy#L23

Then in our test we run the task `build` twice passing the `--build-cache` flag -> https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/cache-rule-issue/src/test/groovy/gradle5/rc/issue/MyPluginSpec.groovy#L79

We expected the second result to not include the `Executing CacheableStatusRule` string in the output, however it shows up.

We also made sure that `project.gradle.startParameter.buildCacheEnable` is `true`

Please let us know if this is an issue or probably we are doing something wrong? or this isn't the expected behavior. Also if you have a better/suggested way to test `CacheableRule` will be much appreciated it

**Comment by ljacomet** [comment]
@rpalcolea The issue you are facing is due to (at least) [these lines](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/cache-rule-issue/src/main/groovy/gradle5/rc/issue/StatusAttribute.groovy#L55-L64) which add a component metadata rule which is not class based.

Currently, these rules are totally opaque to Gradle and thus we cannot guarantee they are not side-effect free. Because of this, caching of metadata processed by component metadata rules is only possible if _all_ rules are class based and _at least one_ is marked `@CacheableRule`.
So in your sample, you will need to update all rules to be class based.

**Comment by ljacomet** [comment]
In addition, the caching of class based component metadata rules is handled through the dependency management level cache and is not tied to the use of the build cache.

At a high level, here is what you get with the dependency management cache:
* Application of rules is always cached within a single build execution. That is once a set of rules have been applied to a module A, further use of this module will not trigger the rules again. Note that this behavior has unfortunate side effects - see #18 
* If rules application can be cached, a subsequent build _on the same machine, from the same project location_ will load the transformed metadata from cache and reuse this result, skipping rules.

There is currently no support for such transform to be cached beyond local build execution.

**Comment by ljacomet** [comment]
And to be even more specific, a way to force execution of rules is by using `--refresh-dependencies`

**Comment by rpalcolea** [comment]
Hi @ljacomet Thanks for the great explanation. It makes sense to me now.

I was able to get it working with `5.0-20180923235913+0000`

However when using `5.0-20180930235830+0000` I get the following exception 

```
org.gradle.api.GradleException: Build aborted because of an internal error.
	at nebula.test.functional.internal.DefaultExecutionResult.rethrowFailure(DefaultExecutionResult.groovy:97)
	at nebula.test.IntegrationSpec.runTasksSuccessfully(IntegrationSpec.groovy:149)
	at gradle5.rc.issue.MyPluginSpec.specific transitive candidates or snapshots resolved(MyPluginSpec.groovy:79)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Could not add entry '60665ab74198089febc169942a6cdb17' to cache md-rule.bin (/Users/rperezalcolea/.gradle/caches/5.0-20180930235830+0000/md-rule/md-rule.bin).
	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74)
	at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:49)
	at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:72)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)

Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.google.common.collect.ImmutableList
	at org.gradle.internal.component.external.model.maven.RealisedMavenModuleResolveMetadata.transform(RealisedMavenModuleResolveMetadata.java:77)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleComponentResolveMetadataSerializer.transformToRealisedForSerialization(ModuleComponentResolveMetadataSerializer.java:91)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleComponentResolveMetadataSerializer.write(ModuleComponentResolveMetadataSerializer.java:72)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleComponentResolveMetadataSerializer.write(ModuleComponentResolveMetadataSerializer.java:42)
	at org.gradle.internal.resolve.caching.CrossBuildCachingRuleExecutor$CacheEntrySerializer.write(CrossBuildCachingRuleExecutor.java:292)
	at org.gradle.internal.resolve.caching.CrossBuildCachingRuleExecutor$CacheEntrySerializer.write(CrossBuildCachingRuleExecutor.java:237)
```

**Comment by rpalcolea** [comment]
Full stacktrace just in case -> https://gist.github.com/rpalcolea/9b3b449230234e6c1b41a027fb43ee92

**Comment by rpalcolea** [comment]
I wonder if the line 77 should be changed to 

`ImmutableList<ModuleDependencyMetadata> dependencies = ImmutableList.builder().addAll(Cast.uncheckedCast(derivedVariant.getDependencies())).build();`

**Comment by rpalcolea** [comment]
Let me know if this helps -> https://github.com/gradle/gradle/pull/6978

**Comment by ljacomet** [comment]
Fix has been merged to master and should be in latest nightly `5.0-20181007235844+0000`

**Comment by rpalcolea** [comment]
This is verified, closing now!
