### ISSUE TITLE
Build-scans plugin 1.x breaks with gradle 5

### ISSUE THREAD

**Issue by rpalcolea** [nebula-plugins/gradle-nebula-integration#45]
Hi folks,

I noticed the following error when using build scans plugin 1.x

```
java.lang.NoClassDefFoundError: org/gradle/internal/operations/notify/BuildOperationNotificationListener2
        at com.gradle.scan.plugin.internal.i.i.a(SourceFile:19)
        at com.gradle.scan.plugin.internal.i.g.a(SourceFile:45)
        at com.gradle.scan.plugin.internal.i.g.a(SourceFile:25)
        at com.gradle.scan.plugin.BuildScanPlugin.a(SourceFile:448)
        at com.gradle.scan.plugin.BuildScanPlugin.a(SourceFile:416)
        at com.gradle.scan.plugin.BuildScanPlugin.apply(SourceFile:257)
        at com.gradle.scan.plugin.BuildScanPlugin.apply(SourceFile:130)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
```

Looks like the change was introduced on this pull request -> https://github.com/gradle/gradle/pull/7023/files

I guess is expected that gradle 5 uses build-scans 2.+ ?

Right now we can't introduce this RC as part of our workflow because it would break backwards compatibility since build scans 2.x is not compatible with Gradle 5. Specially if we introduce this in nebula plugin-plugin which is the base for multiple plugins and also provides build scan to projects using nebula

**Comment by ljacomet** [comment]
@rpalcolea Thanks for the report and making sure. I confirm this is expected.

**Comment by rpalcolea** [comment]
Thanks for confirming, closing now
