### ISSUE TITLE
Dependency download retries with repository bad credentials

### ISSUE THREAD

**Issue by rpalcolea** [nebula-plugins/gradle-nebula-integration#49]
Hi folks!

Some context:

We were applying the following `init.gradle` to one of our test projects that use nebula:

```
allprojects {
    buildscript {
        repositories {
        maven {
                     name 'internal-plugin-portal'
                     url 'https://repo.test.netflix.net/artifactory/gradle-plugins' }
                     }
    }
    repositories {
    maven {
                 name 'internal-plugin-portal'
                 url 'https://repo.test.netflix.net/artifactory/gradle-plugins' }

    }
}
```

While building our project using this script in Gradle 4.10.2 there were no issues, but 5.1 nightly was running out of memory and after increasing the heap size it took 13 min to build vs the usual 1 min.

We started looking into why this happened. One thing that we found is that when we applied this gradle script in gradle 4.10.2 we saw multiple errors like this one

```
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://repo.test.netflix.net/artifactory/gradle-plugins/org/apache/apache/5/apache-5.pom'.
Caused by: java.lang.NullPointerException
    at org.gradle.internal.resource.transport.http.ntlm.NTLMCredentials.<init>(NTLMCredentials.java:35)
```

Thankfully, the error message got enriched in https://github.com/gradle/gradle/issues/6369 https://github.com/gradle/gradle/pull/6379.

With nightly release we found the following:

```
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://repo.test.netflix.net/artifactory/gradle-plugins/org/apache/apache/5/apache-5.pom'.
Caused by: java.lang.NullPointerException: Username must not be null!
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:906)
    at org.gradle.internal.resource.transport.http.ntlm.NTLMCredentials.<init>(NTLMCredentials.java:36)
```

At this point it was clear to us that the issue was credentials related and then we noticed the retries:

```
02:20:02.788 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess] Error while accessing remote repository 622fcde3bac6a47b8e324d8bbe011e59. Waiting 1000ms before next retry. 2 retries left

02:20:03.791 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess] Error while accessing remote repository 622fcde3bac6a47b8e324d8bbe011e59. Waiting 2000ms before next retry. 1 retries left
```

After the 13 min we found around 1.1k retries in our project due to the bad credentials.

Our fix was to not use a repository that requires credentials without them 😅. We didn't notice this issue (and it's been months already probably) before because we didn't have retries so retries are great! 

I believe the feedback goes more into if it is possible to avoid retries when there aren't credentials or valid credentials for a repository.  Without debugging there are two potential scenarios for users:

1) If the dependency graph is small, they might not run out of memory and just see a "slow" build.
2) With big project, they might run out of memory like us

**Comment by melix** [comment]
While I understand that it retries, I'm confused by the out of memory error. Any chance you can post a memory snapshot when this happens?

**Comment by rpalcolea** [comment]
Here is the dump that it's capture when it goes out memory 

Captured with -XX:+HeapDumpOnOutOfMemoryError  flag

[gradle-dependency-download-memory-dump.zip](https://github.com/nebula-plugins/gradle-nebula-integration/files/2519639/gradle-dependency-download-memory-dump.zip)

**Comment by rpalcolea** [comment]
if it helps, when running out of memory we were able to see the following:

```
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /home/travis/.gradle/caches/journal-1/file-access.bin: Size{200} MaxSize{200}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=21} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /home/travis/.gradle/caches/journal-1/file-access.bin: Size{200} MaxSize{200}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=41} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /home/travis/.gradle/caches/journal-1/file-access.bin: Size{200} MaxSize{200}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=42} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /home/travis/.gradle/caches/journal-1/file-access.bin: Size{200} MaxSize{200}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=61} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cached resource https://repo.test.netflix.net/artifactorydr/build-gradle/netflix/nebula-repos/6.0.0-rc.3.dev.10+alpha.ac55b87/nebula-repos-6.0.0-rc.3.dev.10+alpha.ac55b87.jar is up-to-date (lastModified: Thu Oct 25 09:51:05 GMT 2018).
Cache entries evicted. In-memory cache of /home/travis/.gradle/caches/journal-1/file-access.bin: Size{200} MaxSize{200}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=81} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /home/travis/.gradle/caches/journal-1/file-access.bin: Size{200} MaxSize{200}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=82} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /home/travis/.gradle/caches/journal-1/file-access.bin: Size{200} MaxSize{200}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=101} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /home/travis/.gradle/caches/journal-1/file-access.bin: Size{200} MaxSize{200}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=121} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /home/travis/.gradle/caches/journal-1/file-access.bin: Size{200} MaxSize{200}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=141} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Compiling build file '/home/travis/build/nebula/netflixoss-nebula-integration-test/netflixoss-project/build.gradle' using BuildScriptTransformer.
Git repository not found at /home/travis/build/nebula/netflixoss-nebula-integration-test/netflixoss-project -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a different directory.
```

I'm trying to go back right now and get a new dump and full logs when running out of memory

**Comment by ljacomet** [comment]
In Gradle 5.1 the retry conditions have been reworked and should no longer cause this unwanted effect.
See gradle/gradle#7864

**Comment by rpalcolea** [comment]
I couldn't reproduce with latest nightly (5.1-20181207163352+0000). Closing this now. Thanks @melix
